spring:
    data:
        redis:
            host: 127.0.0.1
            port: 6379
    datasource:
        url: jdbc:h2:mem:test
        username: sa
        password:
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
    jpa:
        defer-datasource-initialization: true
        database-platform: H2
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        properties:
            hibernate:
                format_sql: false
                show_sql: false
    #Java ??? ??? spring data redis? ??(17???? ???? ???)
logging:
    level:
        root: INFO
        com.example.zb_account: DEBUG

